config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'

  get '/tasks/new', to: 'tasks#new', as: :new_task

  post '/tasks', to: 'tasks#create'

  get '/tasks/:id', to: 'tasks#show', as: :task

  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/delete.html.erb
<h1>What task  do you want to delete?</h1>

app/views/tasks/edit.html.erb
<h1>Edit this task</h1>

<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

<p><%= link_to "Back to list", tasks_path %></p>

app/views/tasks/index.html.erb
<h1>Here are all your tasks:</h1>

<% @tasks.each do |task| %>
  <% if task.completed? %>
    <p>[X] -
    <%= link_to task.title, task_path(task.id) %>
    <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-trash"></i></p>
    <% end %>
  <% else %>
    <p>[ ] -
    <%= link_to task.title, task_path(task.id) %>
    <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-trash"></i></p>
    <% end %>
  <% end %>
<% end %>


<p><%= link_to "+ Add new task", new_task_path %></p>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit %>
<% end %>

<p><%= link_to "Back to list", tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<%= @task.details %>

  <% if @task.completed %>
    <p>[X] - This task is completed</p>
  <% else %>
    <p>[ ] - This task is not completed yet</p>
  <% end %>

<p><%= link_to "Back to list", tasks_path %></p>
<p class="btn btn-primary"><%= link_to "+ Edit this task", edit_path %></p>
<p><%= link_to "Destroy this task", task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %></p>